### ISSUE TITLE
Settings header text becomes black when exiting Rose prefs

### ISSUE THREAD

**Issue by Spitemare** [ShyMemoriees/Rose#5]
iPhone 8 (10,1) iOS 13.2.2
Rose version 3.0.1-uwu-1+debug from repo.shymemoriees.me

Dark mode must be activated. Rose can be enabled or disabled.

1. Open Settings app. Settings header is white text on black background. Scrolling down settings header shrinks and background blurs behind it.
2. Open Rose prefs.
3. Hit back to close Rose prefs.
4. Settings header text is now black text on blurred background.

Killing and restarting Settings app restores white settings text.

**Comment by ShyMemoriees** [comment]
Hmm i just tried it but there’s no issue for me
