### ISSUE TITLE
Entering preference pane then leaving it makes the word Settings at the top black on black

### ISSUE THREAD

**Issue by M1staAwesome** [ShyMemoriees/Rose#6]
On 13.2.2 8+. Only happens when dark mode is enabled

**Comment by M1staAwesome** [comment]
![Example](https://user-images.githubusercontent.com/37033149/68999050-6285e680-0880-11ea-9d9c-94f10dc4f22d.jpeg)

**Comment by ShyMemoriees** [comment]
Oh yep i see what you mean, but that’s probably caused by cephei which needs be updated for iOS 13 anyway
