### ISSUE TITLE
Safe mode

### ISSUE THREAD

**Issue by subjut** [ShyMemoriees/Rose#7]
I really like your tweak. Unfortunately, whenever I install any 3.* version, my phone resprings into safe mode. Version 2.2.1 did not have that problem, but I cannot downgrade any more since you switched repo.

I tried deleting all preferences with no success.
I use uncover 3.6.2 on iOS 12.4. on an iPhone 7.

Tweaklist:
13HUD: 1.0.1
7-zip (POSIX): 16.02-1
Activator: 1.9.13-beta5
AdvertIDFaker: 0.0.1
AnimationsBeFast: 1.4.7
AppList: 1.5.15-beta1
AppSync Unified: 65.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Avertas: 10.1.2
Base Structure: 1-5
Batchomatic: 4.1.1
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-2
BrickFix: 1.0.1
BrowserChanger10: 1.1.1
bzip2: 1.0.6-1
CA Certs: 0.0.2
Carrierizer: 1.0.4
CCSupport: 1.2.2
CCVPN: 1.0.3
CellDia: 0.0-beta5
Cephei: 1.13.1-2
ConditionalWiFi4: 1.0.0k
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32-b22
Cydia Substrate: 0.9.7033
Cydia Translations: 1.1.32-b1
Cylinder Nitro: 1.0.0-1
Cylinder: 1.1
CyUicacheWhenNeeded: 0.0.1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Easy Notifications: 2.0
Essential: 0-1
file: 5.35-2
Filza File Manager 64-bit: 3.7.2-6
Find Utilities: 4.6.0-2
Five Icon Dock (iOS 11 & 12): 1.0
Flame: 1.3
Flipswitch: 1.0.16-beta5
FolderAutoClose: 12.0
Gawk: 4.2.1-1
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
GoodWiFi: 0.0-beta5
grep: 3.1-1
gzip: 1.9-1
HideDots: 1.1-2
HYI Repo Icons: 8.0.4
iCleaner: 7.7.5
Jailbreak Resources: 1.0-b26
KSBA: 1.3.5-1
LetMeBlock: 0.0.7.1
LetMeKnow: 1.4.2
libcolorpicker: 1.6.4
libcrashreport: 1.1.0-1
libidn2: 6.1.2-1
libpackageinfo (SparkDev): 1.1.4
libplist: 2.0.0-2
libSubstitrate: 0.0.1-3
libswift4: 4.2.1-2
libsymbolicate: 1.9.0-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
MapsOpener: 1.6
Mega UHB IPv4+6 - iOS 9/10/11/12 - MUHB IPv4+6 (Mega Untrusted Hosts Blocker IPv4 and IPv6): 2.1.1
MobileSubstrate Dummy Package: 0.9.7033+dummy
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
No Voice Control: 1.0-1
NoDockGround: 1.0.4
NoLargeTitles: 1.1
Opener: 3.2.2
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PowerLess: 1.1
PowerSelector (iOS 11 & 12): 1.2.1
PreferenceLoader: 2.2.4-beta1
Profile Directory: 0-1
QuickCC: 1.0.4
readline: 8.0-1
RealCC: 1.0.2
ReProvision: 0.5-experimental4
RocketBootstrap: 1.0.7~beta3
rsync: 3.1.3-2
sed: 4.5-1
SelectionPlus: 1.0.6.4
shell-cmds: 118-8
Signing Certificate: 0.0.1
SmallVolumeStep: 1.1.0-2
StatusFolder: 1.0.2
StatusSwitcher: 1.1.1
Substrate Safe Mode: 0.9.6003
Succession: 1.4.3
SugarCane: 1.0.0
SwipeExpander: 1.0.11-1
SwipeSelection: 1.5.2-1
SwipeSelectionFix: 1.2
System Info: 2.0.0-1
System Memory Reset Fix: 2.0
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TapVideoConfig: 0.0.4.2
TechSupport Framework: 1.5.0.1-1
Trust Cache Injector: 0.4-b5
TSS Saver: 1.2.0
tweakCompatible: 0.1.5
TweakConfigurator: 0.3-2
UHB - iOS 9/10/11/12 (Untrusted Hosts Blocker): 1.7.1
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
XZ Utils: 5.2.4-4
YouTube Tools: 2.0
zip: 2.32-1

**Comment by ShyMemoriees** [comment]
Heya!~
Could you retry it be uninstalling Rose firstly. Then open filza and go to /var/mobile/Library/Preferences/ and delete me.shymemoriees.rose . Then run icleaner and install Rose again 😊

**Comment by subjut** [comment]
The iCleaner step did the trick. I did do all the rest, but not that. It's working now. Thanks!
